kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean package
      - mvn test -B
    volumes:
      - name: m2
        path: /root/.m2

  - name: archive-standard-artifact
    image: alpine:latest
    commands:
      - mkdir -p /builds/ns-usbloader
      - cp target/ns-usbloader-*jar /builds/ns-usbloader/
    volumes:
      - name: builds
        path: /builds

  - name: make-store-legacy-artifact
    image: maven:3-jdk-11
    commands:
      - sed -z -i -e 's/<groupId>org.usb4java<\/groupId>\n\s*<artifactId>usb4java<\/artifactId>\s*<version>1.3.0<\/version>/<groupId>org.usb4java<\/groupId>\n<artifactId>usb4java<\/artifactId>\n<version>1.2.0<\/version>/g' pom.xml
      - sed -z -i -e 's/<finalName>${project.artifactId}-${project.version}-${maven.build.timestamp}<\/finalName>/<finalName>${project.artifactId}-legacy-${project.version}-${maven.build.timestamp}<\/finalName>/g' pom.xml
      - mvn -B -DskipTests clean package
      - cp target/ns-usbloader-*jar /builds/ns-usbloader/
    volumes:
      - name: m2
        path: /root/.m2

volumes:
  - name: m2
    host:
      path: /home/docker/drone/files/m2
  - name: builds
    host:
      path: /home/www/builds