kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
    - mvn -B -DskipTests clean package
    - mvn test -B
    volumes:
    - name: m2
      path: /root/.m2

  - name: archive-standard-artifact
    image: alpine:latest
    commands:
    - mkdir -p /builds/ns-usbloader
    - cp target/ns-usbloader-*jar /builds/ns-usbloader/
    volumes:
    - name: builds
      path: /builds

  - name: emerge-legacy-artifact
    image: maven:3-jdk-11
    commands:
    - . ./.make_legacy
    - mvn -B -DskipTests clean package
    - cp target/ns-usbloader-*jar /builds/ns-usbloader/
    volumes:
    - name: m2
      path: /root/.m2
    - name: builds
      path: /builds

volumes:
  - name: m2
    host:
      path: /home/docker/drone/files/m2
  - name: builds
    host:
      path: /home/www/builds
